package demo_game.Inputs;

public enum Action {
    QUIT,
    TOGGLE_FULLSCREEN,
    JUMP,
    CROUCH,
    MOVE_NORTH,
    MOVE_SOUTH,
    MOVE_EAST,
    MOVE_WEST,
    SPRINT,
    TOGGLE_CAMERA_MODE,
    TOGGLE_CHUNK_RENDERING_MODE,
    INVENTORY_TOGGLE,
    CHUNK_POS_LOG,
    RAYCASTING_LOG,
    PLACE_BLOCK,
    BREAK_BLOCK
}
